//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public int ID_cli { get; set; }
        public string NOME_USUARIO { get; set; }
        public string LOGIN { get; set; }
        public string EMAIL { get; set; }
        public string SENHA { get; set; }
    }
}
